### PR TITLE
Test improvements (and some incidental bugfixes)

### PR DESCRIPTION
**Pull request by akx**
Tangentially related to #5, I decided to make sure the test suite runs properly.

On the way, looking at test coverage I discovered a couple corner cases that weren't tested and actually didn't work properly. (ee3e927 fixes those.)

In addition, the project is now testable using [py.test](http://pytest.org/latest/contents.html#) straight out of the box.

### CODE REVIEW

**Comment by vdboor** [comment]
Thanks a lot! Glad to see some testing being added too.

Just wondering, why did you choose to use pytest instead of the Django unittests?
(For example, see how django-parler provides a `runtests.py` that can also be used from `setup.py test`: https://github.com/edoburu/django-parler/blob/master/runtests.py)

**Comment by akx** [comment]
Simply because I'm familiar with py.test :)

However I elected not to port the existing tests to py.test's function-style tests; py.test will happily run `django.test.TestCase`s (`unittest.TestCase`s) too.

**Comment by akx** [comment]
Also, I added a runtests.py similar to the one in django-parler.

**Comment by vdboor** [comment]
Thanks for the work, finally reserved some time, and merged this code!

**Pull request merged**
