### PR TITLE
Validate empty translations (i.e. {}), minor fixes, test improvements

### PR DESCRIPTION
**Pull request by AdrianLC**
Hello,

Sorry this should probably be in separate pull requests but I had some bug fixes directly on my fork and could not sync with upstream until today.

The changes are:
* Current implementation accepts empty translations as valid. I.e. `'translations': {}` and so we encountered objects without translated texts in any language, which in our case and in most I supposed are pretty much useless.
 I added an `allow_empty` option similar to the one in RelatedFields to ``TranslatedFieldsField`. This is disabled by default but can be explicitly declared to maintain the previous behaviour.
* Insert ``.validated_data`` in the translations ``to_internal_value`` instead of directly ``.data``. I honestly do not remember the exact reason to this but I'm certain it had something to do with nested relations and a nested ``SlugRelatedField`` not being restored. Anyway the parent serializers always expect ``validated_data`` to save the children objects as needed.
* Some tests were broken because of translation caching and the pk being always the same due to the automatic database rollback.
* Some pep8 and name fixes.

I leave the version numbering to you. 1.4 probably?

We've being using this in production for months now and I have to use it in another project where Github dependencies are not allowed so if you could please, please release to PyPI as soon as possible... it would be really helpful to us. I will have to copy the whole directory in the meantime as I absolutely don't want to release a fork to PyPI.

Thank you!

### CODE REVIEW

**Comment by vdboor** [comment]
Hi! sorry for not getting back earlier to this.

While the pull request is pretty huge (typically hard to merge), it has many good points. The only think I don't like, is the `allow_empty`. Would it be possible to use the default `required` field instead?

Though I don't like the fact it's a breaking change (for apps that have multiple translation blocks, e.g. models with subclasses), it would be ok with me when it means we fixed the usage of the `Field.required` flag.

**Comment by AdrianLC** [comment]
Hi,

If I'm not mistaken `required` is for whether or not the field must be present, as in the key is in the input data. That validation already worked as expected.
This prevents accepting an empty dictionary of translations and so it felt closer to `allow_blank` or [allow_empty](http://www.django-rest-framework.org/topics/3.2-announcement/#manytomany-fields-and-blanktrue).

Also, in the a use case of deleting translations, someone might still want the field to be `required` while accepting a request to delete all the translations with `'translations': {}`.

It might be clearer with examples:
```python
{
   # whichever fields, but no 'translations'
}
```

Accepted only if `required=False` even if `allow_empty=True`.
Use case could be a project with automatic translations where manual translations are preferred.
but still filled by the backend if not present.

```python
{
   'translations': {}
}
```

Accepted only if `allow_empty=True`, even if `required=True`.
Use case: deleting all existing translations.

**Comment by vdboor** [comment]
Thanks for claring that up, this makes sense to me! I also see the similarities with the `CharField` allow_blank, so it's pretty much in line with the rest.

I've merged the fix, and released it as 1.3!

**Comment by AdrianLC** [comment]
Hi again,

Just noticed, https://github.com/edoburu/django-parler-rest/pull/13 and my commit https://github.com/edoburu/django-parler-rest/commit/e32eeaa6d1c84d1dfe4d7cc8aaef5b61d3d3bd65 solve the same issue. We should probably revert one. Mine is a bit dirty with name changes though. Sorry :(

**Comment by vdboor** [comment]
Which parts would you like to see reversed? I've merged both now, and tests run nicely again.

**Comment by AdrianLC** [comment]
I would just remove the `tearDown`. There's no need to clean up the cache with deletes if it's already disabled in the `setUp`.

**Pull request merged**
